services:

  vera-backend:
    image: ghcr.io/lux-ai-factory/a4s-backend:latest
    ports:
      - "8000:8000"
    container_name: backend
    depends_on:
      - postgres


  vera-webapp:
    image: ghcr.io/lux-ai-factory/a4s-webapp:django-port-integrations
    volumes:
      - vera-webapp-node-modules:/app/node_modules
    ports:
      - "5173:5173"
    container_name: webapp
    depends_on:
      - vera-backend
    env_file:
      - .env


  vera-eval:
    image: ghcr.io/lux-ai-factory/a4s-eval:django-port-integrations
    ports:
      - "8001:8001"
    container_name: eval
    restart: unless-stopped
    depends_on:
      - rabbitmq
    env_file:
      - .env


volumes:
  vera-webapp-node-modules:
