services:

  aisc-backend:
    image: ghcr.io/lux-ai-factory/aisc-backend:latest
    ports:
      - "8000:8000"
    container_name: backend
    depends_on:
      - postgres


  aisc-webapp:
    image: ghcr.io/lux-ai-factory/aisc-webapp:django-port-integrations
    volumes:
      - aisc-webapp-node-modules:/app/node_modules
    ports:
      - "5173:5173"
    container_name: webapp
    depends_on:
      - aisc-backend
    env_file:
      - .env


  aisc-eval:
    image: ghcr.io/lux-ai-factory/aisc-eval:django-port-integrations
    ports:
      - "8001:8001"
    container_name: eval
    restart: unless-stopped
    depends_on:
      - rabbitmq
    env_file:
      - .env


volumes:
  aisc-webapp-node-modules:
