--
-- PostgreSQL database dump
--



SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: engine; Type: SCHEMA; Schema: -; Owner: -
--



--
-- Name: SCHEMA engine; Type: COMMENT; Schema: -; Owner: -
--



SET default_tablespace = '';


--
-- Name: account_emailaddress; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.account_emailaddress (
    id integer NOT NULL,
    email character varying(254) NOT NULL,
    verified boolean NOT NULL,
    "primary" boolean NOT NULL,
    user_id integer NOT NULL
);


--
-- Name: account_emailaddress_id_seq; Type: SEQUENCE; Schema: engine; Owner: -
--

ALTER TABLE engine.account_emailaddress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME engine.account_emailaddress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_emailconfirmation; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.account_emailconfirmation (
    id integer NOT NULL,
    created timestamp with time zone NOT NULL,
    sent timestamp with time zone,
    key character varying(64) NOT NULL,
    email_address_id integer NOT NULL
);


--
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE; Schema: engine; Owner: -
--

ALTER TABLE engine.account_emailconfirmation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME engine.account_emailconfirmation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_component; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.ai_component (
    id bigint NOT NULL,
    pid uuid NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    data character varying(255) NOT NULL,
    file_size bigint,
    storage_container character varying(255) NOT NULL,
    component_type character varying(50) NOT NULL,
    json_value jsonb NOT NULL,
    source_dataset_id bigint,
    system_id bigint NOT NULL
);


--
-- Name: ai_system; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.ai_system (
    id bigint NOT NULL,
    pid uuid NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    project_id bigint NOT NULL
);


--
-- Name: aisc_backend_aicomponent_id_seq; Type: SEQUENCE; Schema: engine; Owner: -
--

ALTER TABLE engine.ai_component ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME engine.aisc_backend_aicomponent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: aisc_backend_aisystem_id_seq; Type: SEQUENCE; Schema: engine; Owner: -
--

ALTER TABLE engine.ai_system ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME engine.aisc_backend_aisystem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: artifact; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.artifact (
    id bigint NOT NULL,
    pid uuid NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    data character varying(255) NOT NULL,
    storage_container character varying(255) NOT NULL,
    evaluation_plugin_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    file_size bigint
);


--
-- Name: aisc_backend_artifact_id_seq; Type: SEQUENCE; Schema: engine; Owner: -
--

ALTER TABLE engine.artifact ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME engine.aisc_backend_artifact_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evaluation; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.evaluation (
    id bigint NOT NULL,
    pid uuid NOT NULL,
    status character varying(255) NOT NULL,
    task uuid,
    project_id bigint NOT NULL,
    system_id uuid,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: aisc_backend_evaluation_id_seq; Type: SEQUENCE; Schema: engine; Owner: -
--

ALTER TABLE engine.evaluation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME engine.aisc_backend_evaluation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evaluation_input; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.evaluation_input (
    id bigint NOT NULL,
    pid uuid NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    value jsonb NOT NULL,
    component_id bigint NOT NULL,
    evaluation_plugin_id bigint NOT NULL
);


--
-- Name: aisc_backend_evaluationinput_id_seq; Type: SEQUENCE; Schema: engine; Owner: -
--

ALTER TABLE engine.evaluation_input ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME engine.aisc_backend_evaluationinput_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evaluation_plugin; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.evaluation_plugin (
    id bigint NOT NULL,
    pid uuid NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    evaluation_id bigint NOT NULL,
    plugin_config_id bigint,
    error_message text NOT NULL,
    finished_at timestamp with time zone,
    started_at timestamp with time zone,
    status character varying(50) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: aisc_backend_evaluationplugin_id_seq; Type: SEQUENCE; Schema: engine; Owner: -
--

ALTER TABLE engine.evaluation_plugin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME engine.aisc_backend_evaluationplugin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: measurement; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.measurement (
    id bigint NOT NULL,
    pid uuid NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    unit character varying(255),
    "time" timestamp with time zone NOT NULL,
    score double precision NOT NULL,
    error character varying(255),
    uncertainty double precision NOT NULL,
    metric_id bigint NOT NULL,
    observation_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    dimensions jsonb,
    direction character varying(50)
);


--
-- Name: aisc_backend_measurement_id_seq; Type: SEQUENCE; Schema: engine; Owner: -
--

ALTER TABLE engine.measurement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME engine.aisc_backend_measurement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: metric; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.metric (
    id bigint NOT NULL,
    pid uuid NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    type_spec character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: aisc_backend_metric_id_seq; Type: SEQUENCE; Schema: engine; Owner: -
--

ALTER TABLE engine.metric ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME engine.aisc_backend_metric_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: metric_category; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.metric_category (
    id bigint NOT NULL,
    pid uuid NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: aisc_backend_metriccategory_id_seq; Type: SEQUENCE; Schema: engine; Owner: -
--

ALTER TABLE engine.metric_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME engine.aisc_backend_metriccategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: metric_category_metrics; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.metric_category_metrics (
    id bigint NOT NULL,
    metriccategory_id bigint NOT NULL,
    metric_id bigint NOT NULL
);


--
-- Name: aisc_backend_metriccategory_metrics_id_seq; Type: SEQUENCE; Schema: engine; Owner: -
--

ALTER TABLE engine.metric_category_metrics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME engine.aisc_backend_metriccategory_metrics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: observation; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.observation (
    id bigint NOT NULL,
    pid uuid NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    observer character varying(255) NOT NULL,
    tool character varying(255) NOT NULL,
    evaluation_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: aisc_backend_observation_id_seq; Type: SEQUENCE; Schema: engine; Owner: -
--

ALTER TABLE engine.observation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME engine.aisc_backend_observation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plugin; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.plugin (
    id bigint NOT NULL,
    pid uuid NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    project_id bigint NOT NULL,
    current_config_id bigint,
    package_name character varying(255) NOT NULL,
    version character varying(50) NOT NULL,
    display_name character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    enabled boolean NOT NULL,
    catalogue_slug character varying(255)
);


--
-- Name: aisc_backend_plugin_id_seq; Type: SEQUENCE; Schema: engine; Owner: -
--

ALTER TABLE engine.plugin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME engine.aisc_backend_plugin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plugin_config; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.plugin_config (
    id bigint NOT NULL,
    config jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    plugin_id bigint NOT NULL,
    description character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    pid uuid NOT NULL
);


--
-- Name: aisc_backend_pluginconfig_id_seq; Type: SEQUENCE; Schema: engine; Owner: -
--

ALTER TABLE engine.plugin_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME engine.aisc_backend_pluginconfig_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plugin_config_project_config; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.plugin_config_project_config (
    id bigint NOT NULL,
    pid uuid NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    plugin_config_key character varying(255) NOT NULL,
    plugin_config_id bigint NOT NULL,
    project_config_id bigint NOT NULL
);


--
-- Name: aisc_backend_pluginconfigsetting_id_seq; Type: SEQUENCE; Schema: engine; Owner: -
--

ALTER TABLE engine.plugin_config_project_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME engine.aisc_backend_pluginconfigsetting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.project (
    id bigint NOT NULL,
    pid uuid NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    project_id uuid
);


--
-- Name: aisc_backend_project_id_seq; Type: SEQUENCE; Schema: engine; Owner: -
--

ALTER TABLE engine.project ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME engine.aisc_backend_project_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_config; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.project_config (
    id bigint NOT NULL,
    pid uuid NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    key character varying(255) NOT NULL,
    category character varying(50) NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    encrypted_value text NOT NULL,
    masked_value character varying(255) NOT NULL,
    json_value jsonb NOT NULL,
    project_id bigint NOT NULL
);


--
-- Name: aisc_backend_projectsetting_id_seq; Type: SEQUENCE; Schema: engine; Owner: -
--

ALTER TABLE engine.project_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME engine.aisc_backend_projectsetting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: engine; Owner: -
--

ALTER TABLE engine.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME engine.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: engine; Owner: -
--

ALTER TABLE engine.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME engine.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: engine; Owner: -
--

ALTER TABLE engine.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME engine.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: engine; Owner: -
--

ALTER TABLE engine.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME engine.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: engine; Owner: -
--

ALTER TABLE engine.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME engine.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: engine; Owner: -
--

ALTER TABLE engine.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME engine.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: derived; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.derived (
    metric_ptr_id bigint NOT NULL,
    expression character varying(255) NOT NULL,
    base_metric_id bigint NOT NULL
);


--
-- Name: direct; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.direct (
    metric_ptr_id bigint NOT NULL
);


--
-- Name: django_admin_log; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: engine; Owner: -
--

ALTER TABLE engine.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME engine.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: engine; Owner: -
--

ALTER TABLE engine.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME engine.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: engine; Owner: -
--

ALTER TABLE engine.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME engine.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: engine; Owner: -
--

CREATE TABLE engine.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: account_emailaddress account_emailaddress_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.account_emailaddress
    ADD CONSTRAINT account_emailaddress_pkey PRIMARY KEY (id);


--
-- Name: account_emailaddress account_emailaddress_user_id_email_987c8728_uniq; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_email_987c8728_uniq UNIQUE (user_id, email);


--
-- Name: account_emailconfirmation account_emailconfirmation_key_key; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_key_key UNIQUE (key);


--
-- Name: account_emailconfirmation account_emailconfirmation_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_pkey PRIMARY KEY (id);


--
-- Name: ai_component aisc_backend_aicomponent_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.ai_component
    ADD CONSTRAINT aisc_backend_aicomponent_pkey PRIMARY KEY (id);


--
-- Name: ai_system aisc_backend_aisystem_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.ai_system
    ADD CONSTRAINT aisc_backend_aisystem_pkey PRIMARY KEY (id);


--
-- Name: ai_system aisc_backend_aisystem_project_id_key; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.ai_system
    ADD CONSTRAINT aisc_backend_aisystem_project_id_key UNIQUE (project_id);


--
-- Name: artifact aisc_backend_artifact_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.artifact
    ADD CONSTRAINT aisc_backend_artifact_pkey PRIMARY KEY (id);


--
-- Name: derived aisc_backend_derived_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.derived
    ADD CONSTRAINT aisc_backend_derived_pkey PRIMARY KEY (metric_ptr_id);


--
-- Name: direct aisc_backend_direct_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.direct
    ADD CONSTRAINT aisc_backend_direct_pkey PRIMARY KEY (metric_ptr_id);


--
-- Name: evaluation aisc_backend_evaluation_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.evaluation
    ADD CONSTRAINT aisc_backend_evaluation_pkey PRIMARY KEY (id);


--
-- Name: evaluation_input aisc_backend_evaluationi_evaluation_plugin_id_nam_5415cb96_uniq; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.evaluation_input
    ADD CONSTRAINT aisc_backend_evaluationi_evaluation_plugin_id_nam_5415cb96_uniq UNIQUE (evaluation_plugin_id, name);


--
-- Name: evaluation_input aisc_backend_evaluationinput_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.evaluation_input
    ADD CONSTRAINT aisc_backend_evaluationinput_pkey PRIMARY KEY (id);


--
-- Name: evaluation_plugin aisc_backend_evaluationplugin_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.evaluation_plugin
    ADD CONSTRAINT aisc_backend_evaluationplugin_pkey PRIMARY KEY (id);


--
-- Name: measurement aisc_backend_measurement_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.measurement
    ADD CONSTRAINT aisc_backend_measurement_pkey PRIMARY KEY (id);


--
-- Name: metric aisc_backend_metric_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.metric
    ADD CONSTRAINT aisc_backend_metric_pkey PRIMARY KEY (id);


--
-- Name: metric_category_metrics aisc_backend_metriccateg_metriccategory_id_metric_1be78dc7_uniq; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.metric_category_metrics
    ADD CONSTRAINT aisc_backend_metriccateg_metriccategory_id_metric_1be78dc7_uniq UNIQUE (metriccategory_id, metric_id);


--
-- Name: metric_category_metrics aisc_backend_metriccategory_metrics_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.metric_category_metrics
    ADD CONSTRAINT aisc_backend_metriccategory_metrics_pkey PRIMARY KEY (id);


--
-- Name: metric_category aisc_backend_metriccategory_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.metric_category
    ADD CONSTRAINT aisc_backend_metriccategory_pkey PRIMARY KEY (id);


--
-- Name: observation aisc_backend_observation_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.observation
    ADD CONSTRAINT aisc_backend_observation_pkey PRIMARY KEY (id);


--
-- Name: plugin aisc_backend_plugin_name_project_id_version__9895eff6_uniq; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.plugin
    ADD CONSTRAINT aisc_backend_plugin_name_project_id_version__9895eff6_uniq UNIQUE (name, project_id, version, package_name);


--
-- Name: plugin aisc_backend_plugin_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.plugin
    ADD CONSTRAINT aisc_backend_plugin_pkey PRIMARY KEY (id);


--
-- Name: plugin_config aisc_backend_pluginconfig_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.plugin_config
    ADD CONSTRAINT aisc_backend_pluginconfig_pkey PRIMARY KEY (id);


--
-- Name: plugin_config_project_config aisc_backend_pluginconfigsetting_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.plugin_config_project_config
    ADD CONSTRAINT aisc_backend_pluginconfigsetting_pkey PRIMARY KEY (id);


--
-- Name: project aisc_backend_project_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.project
    ADD CONSTRAINT aisc_backend_project_pkey PRIMARY KEY (id);


--
-- Name: project_config aisc_backend_projectsetting_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.project_config
    ADD CONSTRAINT aisc_backend_projectsetting_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: plugin_config_project_config unique_plugin_config_project_config_key; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.plugin_config_project_config
    ADD CONSTRAINT unique_plugin_config_project_config_key UNIQUE (plugin_config_id, plugin_config_key);


--
-- Name: project_config unique_project_config_key; Type: CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.project_config
    ADD CONSTRAINT unique_project_config_key UNIQUE (project_id, category, key);


--
-- Name: account_emailaddress_email_03be32b2; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX account_emailaddress_email_03be32b2 ON engine.account_emailaddress USING btree (email);


--
-- Name: account_emailaddress_email_03be32b2_like; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX account_emailaddress_email_03be32b2_like ON engine.account_emailaddress USING btree (email varchar_pattern_ops);


--
-- Name: account_emailaddress_user_id_2c513194; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX account_emailaddress_user_id_2c513194 ON engine.account_emailaddress USING btree (user_id);


--
-- Name: account_emailconfirmation_email_address_id_5b7f8c58; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX account_emailconfirmation_email_address_id_5b7f8c58 ON engine.account_emailconfirmation USING btree (email_address_id);


--
-- Name: account_emailconfirmation_key_f43612bd_like; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX account_emailconfirmation_key_f43612bd_like ON engine.account_emailconfirmation USING btree (key varchar_pattern_ops);


--
-- Name: aisc_backend_aicomponent_source_dataset_id_aed18047; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX aisc_backend_aicomponent_source_dataset_id_aed18047 ON engine.ai_component USING btree (source_dataset_id);


--
-- Name: aisc_backend_aicomponent_system_id_0909bda5; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX aisc_backend_aicomponent_system_id_0909bda5 ON engine.ai_component USING btree (system_id);


--
-- Name: aisc_backend_artifact_evaluation_plugin_id_a1b64b2e; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX aisc_backend_artifact_evaluation_plugin_id_a1b64b2e ON engine.artifact USING btree (evaluation_plugin_id);


--
-- Name: aisc_backend_derived_base_metric_id_ba6169f6; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX aisc_backend_derived_base_metric_id_ba6169f6 ON engine.derived USING btree (base_metric_id);


--
-- Name: aisc_backend_evaluation_project_id_23e1aa63; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX aisc_backend_evaluation_project_id_23e1aa63 ON engine.evaluation USING btree (project_id);


--
-- Name: aisc_backend_evaluation_system_id_db29add6; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX aisc_backend_evaluation_system_id_db29add6 ON engine.evaluation USING btree (system_id);


--
-- Name: aisc_backend_evaluationinput_component_id_34f724b0; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX aisc_backend_evaluationinput_component_id_34f724b0 ON engine.evaluation_input USING btree (component_id);


--
-- Name: aisc_backend_evaluationinput_evaluation_plugin_id_7c4716b3; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX aisc_backend_evaluationinput_evaluation_plugin_id_7c4716b3 ON engine.evaluation_input USING btree (evaluation_plugin_id);


--
-- Name: aisc_backend_evaluationplugin_evaluation_id_8c122699; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX aisc_backend_evaluationplugin_evaluation_id_8c122699 ON engine.evaluation_plugin USING btree (evaluation_id);


--
-- Name: aisc_backend_evaluationplugin_plugin_config_id_61e5a338; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX aisc_backend_evaluationplugin_plugin_config_id_61e5a338 ON engine.evaluation_plugin USING btree (plugin_config_id);


--
-- Name: aisc_backend_measurement_metric_id_b7e13397; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX aisc_backend_measurement_metric_id_b7e13397 ON engine.measurement USING btree (metric_id);


--
-- Name: aisc_backend_measurement_observation_id_0bcacda6; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX aisc_backend_measurement_observation_id_0bcacda6 ON engine.measurement USING btree (observation_id);


--
-- Name: aisc_backend_metriccategory_metrics_metric_id_09e83070; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX aisc_backend_metriccategory_metrics_metric_id_09e83070 ON engine.metric_category_metrics USING btree (metric_id);


--
-- Name: aisc_backend_metriccategory_metrics_metriccategory_id_95f878da; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX aisc_backend_metriccategory_metrics_metriccategory_id_95f878da ON engine.metric_category_metrics USING btree (metriccategory_id);


--
-- Name: aisc_backend_observation_evaluation_id_b6657f4d; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX aisc_backend_observation_evaluation_id_b6657f4d ON engine.observation USING btree (evaluation_id);


--
-- Name: aisc_backend_plugin_current_config_id_8dec39e8; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX aisc_backend_plugin_current_config_id_8dec39e8 ON engine.plugin USING btree (current_config_id);


--
-- Name: aisc_backend_plugin_project_id_ff74ad16; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX aisc_backend_plugin_project_id_ff74ad16 ON engine.plugin USING btree (project_id);


--
-- Name: aisc_backend_pluginconfig_plugin_id_576d8319; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX aisc_backend_pluginconfig_plugin_id_576d8319 ON engine.plugin_config USING btree (plugin_id);


--
-- Name: aisc_backend_pluginconfigsetting_plugin_config_id_a7373bb2; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX aisc_backend_pluginconfigsetting_plugin_config_id_a7373bb2 ON engine.plugin_config_project_config USING btree (plugin_config_id);


--
-- Name: aisc_backend_pluginconfigsetting_project_setting_id_2d4a3c74; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX aisc_backend_pluginconfigsetting_project_setting_id_2d4a3c74 ON engine.plugin_config_project_config USING btree (project_config_id);


--
-- Name: aisc_backend_project_platform_project_id_f61734b2; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX aisc_backend_project_platform_project_id_f61734b2 ON engine.project USING btree (project_id);


--
-- Name: aisc_backend_projectsetting_project_id_fedf71b7; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX aisc_backend_projectsetting_project_id_fedf71b7 ON engine.project_config USING btree (project_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON engine.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON engine.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON engine.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON engine.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON engine.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON engine.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON engine.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON engine.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON engine.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON engine.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON engine.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON engine.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON engine.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: metric_dimensions_gin; Type: INDEX; Schema: engine; Owner: -
--

CREATE INDEX metric_dimensions_gin ON engine.measurement USING gin (dimensions);


--
-- Name: one_project_per_platform_project; Type: INDEX; Schema: engine; Owner: -
--

CREATE UNIQUE INDEX one_project_per_platform_project ON engine.project USING btree (project_id) WHERE (project_id IS NOT NULL);


--
-- Name: unique_primary_email; Type: INDEX; Schema: engine; Owner: -
--

CREATE UNIQUE INDEX unique_primary_email ON engine.account_emailaddress USING btree (user_id, "primary") WHERE "primary";


--
-- Name: unique_verified_email; Type: INDEX; Schema: engine; Owner: -
--

CREATE UNIQUE INDEX unique_verified_email ON engine.account_emailaddress USING btree (email) WHERE verified;


--
-- Name: account_emailaddress account_emailaddress_user_id_2c513194_fk_auth_user_id; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_2c513194_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES engine.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_emailconfirmation account_emailconfirm_email_address_id_5b7f8c58_fk_account_e; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirm_email_address_id_5b7f8c58_fk_account_e FOREIGN KEY (email_address_id) REFERENCES engine.account_emailaddress(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ai_component aisc_backend_aicompo_source_dataset_id_aed18047_fk_aisc_back; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.ai_component
    ADD CONSTRAINT aisc_backend_aicompo_source_dataset_id_aed18047_fk_aisc_back FOREIGN KEY (source_dataset_id) REFERENCES engine.ai_component(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ai_component aisc_backend_aicompo_system_id_0909bda5_fk_aisc_back; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.ai_component
    ADD CONSTRAINT aisc_backend_aicompo_system_id_0909bda5_fk_aisc_back FOREIGN KEY (system_id) REFERENCES engine.ai_system(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ai_system aisc_backend_aisystem_project_id_381e09a9_fk_project_id; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.ai_system
    ADD CONSTRAINT aisc_backend_aisystem_project_id_381e09a9_fk_project_id FOREIGN KEY (project_id) REFERENCES engine.project(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: artifact aisc_backend_artifac_evaluation_plugin_id_a1b64b2e_fk_aisc_back; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.artifact
    ADD CONSTRAINT aisc_backend_artifac_evaluation_plugin_id_a1b64b2e_fk_aisc_back FOREIGN KEY (evaluation_plugin_id) REFERENCES engine.evaluation_plugin(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: derived aisc_backend_derived_base_metric_id_ba6169f6_fk_aisc_back; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.derived
    ADD CONSTRAINT aisc_backend_derived_base_metric_id_ba6169f6_fk_aisc_back FOREIGN KEY (base_metric_id) REFERENCES engine.metric(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: derived aisc_backend_derived_metric_ptr_id_e8cc6ab1_fk_aisc_back; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.derived
    ADD CONSTRAINT aisc_backend_derived_metric_ptr_id_e8cc6ab1_fk_aisc_back FOREIGN KEY (metric_ptr_id) REFERENCES engine.metric(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: direct aisc_backend_direct_metric_ptr_id_43d04e07_fk_aisc_back; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.direct
    ADD CONSTRAINT aisc_backend_direct_metric_ptr_id_43d04e07_fk_aisc_back FOREIGN KEY (metric_ptr_id) REFERENCES engine.metric(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluation_input aisc_backend_evaluat_component_id_34f724b0_fk_aisc_back; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.evaluation_input
    ADD CONSTRAINT aisc_backend_evaluat_component_id_34f724b0_fk_aisc_back FOREIGN KEY (component_id) REFERENCES engine.ai_component(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluation_plugin aisc_backend_evaluat_evaluation_id_8c122699_fk_aisc_back; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.evaluation_plugin
    ADD CONSTRAINT aisc_backend_evaluat_evaluation_id_8c122699_fk_aisc_back FOREIGN KEY (evaluation_id) REFERENCES engine.evaluation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluation_input aisc_backend_evaluat_evaluation_plugin_id_7c4716b3_fk_evaluatio; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.evaluation_input
    ADD CONSTRAINT aisc_backend_evaluat_evaluation_plugin_id_7c4716b3_fk_evaluatio FOREIGN KEY (evaluation_plugin_id) REFERENCES engine.evaluation_plugin(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluation_plugin aisc_backend_evaluat_plugin_config_id_61e5a338_fk_aisc_back; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.evaluation_plugin
    ADD CONSTRAINT aisc_backend_evaluat_plugin_config_id_61e5a338_fk_aisc_back FOREIGN KEY (plugin_config_id) REFERENCES engine.plugin_config(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluation aisc_backend_evaluat_project_id_23e1aa63_fk_aisc_back; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.evaluation
    ADD CONSTRAINT aisc_backend_evaluat_project_id_23e1aa63_fk_aisc_back FOREIGN KEY (project_id) REFERENCES engine.project(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluation aisc_backend_evaluation_system_id_fkey; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.evaluation
    ADD CONSTRAINT aisc_backend_evaluation_system_id_fkey FOREIGN KEY (system_id) REFERENCES core.system(pid) ON DELETE SET NULL;


--
-- Name: measurement aisc_backend_measure_metric_id_b7e13397_fk_aisc_back; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.measurement
    ADD CONSTRAINT aisc_backend_measure_metric_id_b7e13397_fk_aisc_back FOREIGN KEY (metric_id) REFERENCES engine.metric(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: measurement aisc_backend_measure_observation_id_0bcacda6_fk_aisc_back; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.measurement
    ADD CONSTRAINT aisc_backend_measure_observation_id_0bcacda6_fk_aisc_back FOREIGN KEY (observation_id) REFERENCES engine.observation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: metric_category_metrics aisc_backend_metricc_metric_id_09e83070_fk_aisc_back; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.metric_category_metrics
    ADD CONSTRAINT aisc_backend_metricc_metric_id_09e83070_fk_aisc_back FOREIGN KEY (metric_id) REFERENCES engine.metric(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: metric_category_metrics aisc_backend_metricc_metriccategory_id_95f878da_fk_aisc_back; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.metric_category_metrics
    ADD CONSTRAINT aisc_backend_metricc_metriccategory_id_95f878da_fk_aisc_back FOREIGN KEY (metriccategory_id) REFERENCES engine.metric_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: observation aisc_backend_observa_evaluation_id_b6657f4d_fk_aisc_back; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.observation
    ADD CONSTRAINT aisc_backend_observa_evaluation_id_b6657f4d_fk_aisc_back FOREIGN KEY (evaluation_id) REFERENCES engine.evaluation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: plugin aisc_backend_plugin_current_config_id_8dec39e8_fk_aisc_back; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.plugin
    ADD CONSTRAINT aisc_backend_plugin_current_config_id_8dec39e8_fk_aisc_back FOREIGN KEY (current_config_id) REFERENCES engine.plugin_config(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: plugin aisc_backend_plugin_project_id_ff74ad16_fk_aisc_back; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.plugin
    ADD CONSTRAINT aisc_backend_plugin_project_id_ff74ad16_fk_aisc_back FOREIGN KEY (project_id) REFERENCES engine.project(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: plugin_config_project_config aisc_backend_pluginc_plugin_config_id_a7373bb2_fk_aisc_back; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.plugin_config_project_config
    ADD CONSTRAINT aisc_backend_pluginc_plugin_config_id_a7373bb2_fk_aisc_back FOREIGN KEY (plugin_config_id) REFERENCES engine.plugin_config(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: plugin_config aisc_backend_pluginc_plugin_id_576d8319_fk_aisc_back; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.plugin_config
    ADD CONSTRAINT aisc_backend_pluginc_plugin_id_576d8319_fk_aisc_back FOREIGN KEY (plugin_id) REFERENCES engine.plugin(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: project aisc_backend_project_platform_project_id_fkey; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.project
    ADD CONSTRAINT aisc_backend_project_platform_project_id_fkey FOREIGN KEY (project_id) REFERENCES core.project(pid) ON DELETE SET NULL;


--
-- Name: project_config aisc_backend_project_project_id_fedf71b7_fk_aisc_back; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.project_config
    ADD CONSTRAINT aisc_backend_project_project_id_fedf71b7_fk_aisc_back FOREIGN KEY (project_id) REFERENCES engine.project(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES engine.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES engine.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES engine.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES engine.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES engine.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES engine.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES engine.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES engine.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES engine.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: plugin_config_project_config plugin_config_settin_project_config_id_505b7676_fk_project_s; Type: FK CONSTRAINT; Schema: engine; Owner: -
--

ALTER TABLE ONLY engine.plugin_config_project_config
    ADD CONSTRAINT plugin_config_settin_project_config_id_505b7676_fk_project_s FOREIGN KEY (project_config_id) REFERENCES engine.project_config(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--


