"""Service tokens, one per caller edge.

The service-only APIs (qualification-agents, -ontology, -prefill, -llm, -pdf and controls-pdf)
and the card agent's two routes on qualification-web each accept only the tokens of their own
callers. Each token is generated by scripts/secrets.sh (appended to an existing install, never
replacing a value), required by the compose file as `${NAME:?run scripts/secrets.sh first}`,
commented in env.development and env.staging, and reaches exactly its two ends.

Nothing is started and nothing in the repo is written: secrets.sh runs on a scratch copy and
`docker compose config` reads scratch copies of the compose files.

    uv run --no-project --with pytest python -m pytest -q -p no:cacheprovider scripts/tests/test_service_tokens.py
"""

import json
import os
import re
import shutil
import subprocess

import pytest

from conftest import ROOT
from test_llm_keys import run_secrets, secrets_of

FILES = ["docker-compose-infra.development.yml", "docker-compose.development.yml"]

#: token -> (callee, caller), the two services that may hold it
EDGES = {
    "QUALIFICATION_AGENTS_TO_WEB_TOKEN": ("qualification-web", "qualification-agents"),
    "QUALIFICATION_WEB_TO_AGENTS_TOKEN": ("qualification-agents", "qualification-web"),
    "QUALIFICATION_WEB_TO_ONTOLOGY_TOKEN": ("qualification-ontology", "qualification-web"),
    "QUALIFICATION_AGENTS_TO_ONTOLOGY_TOKEN": ("qualification-ontology", "qualification-agents"),
    "QUALIFICATION_WEB_TO_PREFILL_TOKEN": ("qualification-prefill", "qualification-web"),
    "QUALIFICATION_WEB_TO_LLM_TOKEN": ("qualification-llm", "qualification-web"),
    "QUALIFICATION_WEB_TO_PDF_TOKEN": ("qualification-pdf", "qualification-web"),
    "CONTROLS_WEB_TO_PDF_TOKEN": ("controls-pdf", "controls-web"),
}

#: the door module, one file with the same bytes in every service that has it
DOOR_COPIES = [
    "apps/qualification/services/agents/service_token.py",
    "apps/qualification/services/ontology/service_token.py",
    "apps/qualification/services/prefill/service_token.py",
    "apps/qualification/services/system_card_renderer/service_token.py",
    "apps/qualification/services/llm/service_token.py",
    "apps/controls/services/pdf_renderer/service_token.py",
]


def config(tmp_path, values):
    args, required = [], set()
    for f in FILES:
        shutil.copy(ROOT / f, tmp_path / f)
        args += ["-f", str(tmp_path / f)]
        required |= set(re.findall(r"\$\{([A-Z0-9_]+):\?", (ROOT / f).read_text()))
    env = {**os.environ, **{k: "dummy" for k in required}, **values}
    j = subprocess.run(["docker", "compose", "-p", "aisc-t-config", "--project-directory", str(ROOT),
                        "--env-file", str(ROOT / "env.development"), *args, "config", "--format", "json"],
                       env=env, capture_output=True, text=True)
    assert j.returncode == 0, j.stderr[-2000:]
    return json.loads(j.stdout)["services"], required


@pytest.fixture(scope="module")
def wired(tmp_path_factory):
    values = {name: f"value-of-{name.lower()}" for name in EDGES}
    services, required = config(tmp_path_factory.mktemp("tokens"), values)
    return services, required, values


def test_every_token_is_a_required_compose_variable(wired):
    _, required, _ = wired
    missing = sorted(set(EDGES) - required)
    assert not missing, f"not given as ${{NAME:?run scripts/secrets.sh first}}: {missing}"
    text = (ROOT / "docker-compose.development.yml").read_text()
    for name in EDGES:
        assert f"${{{name}:?run scripts/secrets.sh first}}" in text, name


@pytest.mark.parametrize("name", sorted(EDGES))
def test_each_token_reaches_exactly_its_two_ends(wired, name):
    services, _, values = wired
    holders = sorted(s for s, svc in services.items()
                     if values[name] in (svc.get("environment") or {}).values())
    assert holders == sorted(EDGES[name]), name
    for holder in EDGES[name]:
        env = services[holder].get("environment") or {}
        assert env.get(name) == values[name], f"{holder} holds it under another name"


def test_each_service_holds_only_the_tokens_it_needs(wired):
    services, _, values = wired
    by_value = {v: k for k, v in values.items()}
    for svc_name, svc in services.items():
        held = {by_value[v] for v in (svc.get("environment") or {}).values() if v in by_value}
        needed = {n for n, ends in EDGES.items() if svc_name in ends}
        assert held == needed, svc_name


def test_the_platform_tokens_are_left_as_they_were(wired):
    services, _, _ = wired
    assert services["qualification-agents"]["environment"]["PLATFORM_INTERNAL_TOKEN"] == "dummy"
    platform = services["platform"]["environment"]
    assert platform["PLATFORM_CARD_AGENT_TOKEN"] == "dummy"
    assert platform["PLATFORM_RISK_MAPPER_TOKEN"] == "dummy"


# secrets.sh, on a scratch copy only


@pytest.fixture
def scratch(tmp_path):
    (tmp_path / "scripts").mkdir()
    (tmp_path / "keycloak").mkdir()
    shutil.copy(ROOT / "scripts/secrets.sh", tmp_path / "scripts/secrets.sh")
    shutil.copy(ROOT / "keycloak/aisc-realm.json", tmp_path / "keycloak/aisc-realm.json")
    shutil.copy(ROOT / "env.plugin_downloader", tmp_path / "env.plugin_downloader")
    return tmp_path


def check_tokens(values):
    for name in EDGES:
        assert re.fullmatch(r"[0-9a-f]{64}", values.get(name, "")), name
    assert len({values[n] for n in EDGES}) == len(EDGES), "two edges share one value"


def test_a_new_install_gets_every_token_and_a_second_run_keeps_them(scratch):
    run_secrets(scratch)
    first = secrets_of(scratch)
    check_tokens(first)
    run_secrets(scratch)
    assert secrets_of(scratch) == first


def test_an_existing_install_gets_them_appended_without_replacing_anything(scratch):
    old = {"GATEWAY_COOKIE_SECRET": "c" * 43, "GATEWAY_CLIENT_SECRET": "old-client",
           "PLATFORM_CARD_AGENT_TOKEN": "old-card", "PLATFORM_RISK_MAPPER_TOKEN": "old-risk",
           "QUALIFICATION_WEB_TO_PDF_TOKEN": "old-pdf"}
    (scratch / "env.secrets").write_text("# made before\n" + "".join(f"{k}={v}\n" for k, v in old.items()))
    run_secrets(scratch)
    values = secrets_of(scratch)
    for k, v in old.items():
        assert values[k] == v, k
    for name in set(EDGES) - set(old):
        assert re.fullmatch(r"[0-9a-f]{64}", values[name]), name
    first = dict(values)
    run_secrets(scratch)
    assert secrets_of(scratch) == first


def test_rotate_makes_new_distinct_tokens(scratch):
    run_secrets(scratch)
    before = secrets_of(scratch)
    r = subprocess.run(["bash", str(scratch / "scripts/secrets.sh"), "--rotate"], cwd=scratch,
                       capture_output=True, text=True, timeout=120)
    assert r.returncode == 0, r.stderr[-2000:]
    after = secrets_of(scratch)
    check_tokens(after)
    for name in EDGES:
        assert after[name] != before[name], name


# env comments and the door module


@pytest.mark.parametrize("name", ["env.development", "env.staging"])
def test_env_files_say_where_each_token_comes_from(name):
    text = (ROOT / name).read_text()
    comments = [line for line in text.splitlines() if line.startswith("#")]
    for token in EDGES:
        assert any(token in line and "env.secrets" in line for line in comments), f"{name}: {token}"
        assert not re.search(rf"^{token}=", text, re.M), f"{name} must not set {token}"


def test_the_door_module_is_one_file_in_every_service():
    texts = {path: (ROOT / path).read_bytes() for path in DOOR_COPIES}
    assert len(set(texts.values())) == 1, "the copies of service_token.py differ"


@pytest.mark.parametrize("path", DOOR_COPIES)
def test_the_door_is_built_into_the_image(path):
    """Each service's Dockerfile copies service_token.py next to its app."""
    service_dir = (ROOT / path).parent
    dockerfile = (service_dir / "Dockerfile").read_text()
    rel = service_dir.name
    sources = []
    for line in re.findall(r"^COPY\s+(.+)$", dockerfile, re.M):
        parts = [p for p in line.split() if not p.startswith("--")]
        sources += parts[:-1]
    assert any(s in (".", "./") or s.rstrip("/") == f"services/{rel}" or s.endswith(f"{rel}/service_token.py")
               for s in sources), f"{rel}/Dockerfile does not copy service_token.py: {sources}"
