#!/usr/bin/env bash
# The secrets this install runs on, generated here and never committed.
#
#   ./scripts/secrets.sh            # make them if they are missing
#   ./scripts/secrets.sh --rotate   # make new ones, replacing what is there
#
# A secret committed to the repo is a secret every clone shares. The worst of
# them would be the gateway's cookie secret: whoever holds it can mint a
# session cookie for any user, offline, and that cookie is the session every
# module trusts.
#
# So none of them has a default. The compose files refuse to start without
# these, this writes them once into env.secrets, which is git-ignored, and the
# realm import is rendered from its template with the same values.
#
# PLATFORM_SECRETS_KEY is the exception to --rotate: it encrypts the LLM API keys
# stored in every project's database, so a fresh one would make all of them
# unreadable. --rotate keeps it. To rotate it: prepend a new Fernet key to it
# (comma list, newest first), restart the platform, run
#   python -m platform_service.llm_store rotate
# in the platform container, then drop the old key from the list.
set -euo pipefail
cd "$(dirname "$0")/.."
# Every file written here holds secrets or is made from them: private from the moment it exists,
# not only after the chmod further down.
umask 077

OUT=env.secrets
COMBINED=env.runtime   # what compose is pointed at: the settings plus the secrets
TEMPLATE=keycloak/aisc-realm.json
RENDERED=keycloak/aisc-realm.local.json

rand()      { openssl rand -hex 32; }
# oauth2-proxy decodes this as base64url and wants exactly 32 bytes out. With
# padding it does not decode, and it then measures the string itself and
# refuses to start: "cookie_secret must be 16, 24, or 32 bytes ... but is 44".
cookie()    { openssl rand -base64 32 | tr '+/' '-_' | tr -d '=\n'; }
# Fernet wants urlsafe base64 of 32 bytes WITH its `=` padding: 44 characters.
fernet()    { openssl rand -base64 32 | tr '+/' '-_' | tr -d '\n'; }

# Every secret, in the order a new env.secrets lists them, as NAME=kind of value it takes.
# A secret added here reaches existing installs too: the loop below appends whatever an
# env.secrets lacks, never replacing a value that is there.
SECRETS=(
GATEWAY_COOKIE_SECRET=cookie
GATEWAY_CLIENT_SECRET=rand
CATALOGUE_INSTALL_TOKEN=rand
DJANGO_SECRET_KEY=rand
INTERNAL_API_KEY=rand
SUPERSET_SECRET_KEY=rand
DASHBOARD_ADMIN_PASSWORD=rand
# the platform's calls to the dashboard's bridge (/api/v1/aisc_project); with none, it refuses them all
DASHBOARD_BRIDGE_TOKEN=rand
REPORT_SERVICE_TOKEN=rand
REPORT_RO_PASSWORD=rand
REPORT_COMPOSER_PASSWORD=rand
INSPECTOR_PASSWORD=rand
# One token per agentic system, so each agent resolves only its own choice and key.
PLATFORM_CARD_AGENT_TOKEN=rand
PLATFORM_RISK_MAPPER_TOKEN=rand
# One token per caller edge of the service-only APIs (API auth, 2026-09-25): each
# is held by its caller and its callee only, so no service can call another with
# a token it was not given.
QUALIFICATION_AGENTS_TO_WEB_TOKEN=rand
QUALIFICATION_WEB_TO_AGENTS_TOKEN=rand
QUALIFICATION_WEB_TO_ONTOLOGY_TOKEN=rand
QUALIFICATION_AGENTS_TO_ONTOLOGY_TOKEN=rand
QUALIFICATION_WEB_TO_PREFILL_TOKEN=rand
QUALIFICATION_WEB_TO_LLM_TOKEN=rand
QUALIFICATION_WEB_TO_PDF_TOKEN=rand
CONTROLS_WEB_TO_PDF_TOKEN=rand
PLATFORM_SECRETS_KEY=fernet
)
value_of() { case "$1" in cookie) cookie ;; fernet) fernet ;; *) rand ;; esac; }

# A value of NAME in a file: empty when the line is missing or has no value.
value_in() { awk -v n="$1" 'index($0, n "=") == 1 { print substr($0, length(n) + 2); exit }' "$2"; }
# A new value, or empty when openssl failed (set -e would otherwise stop without a word).
fresh()    { value_of "$1" || true; }

# The LLM keys' encryption key survives --rotate (see the top of this file).
secrets_key=""
if [ -f "$OUT" ]; then
  secrets_key=$(value_in PLATFORM_SECRETS_KEY "$OUT")
fi

# The new env.secrets is built beside the old one and moved into place at the end, so a run that
# fails (openssl, a full disk) leaves the old file as it was.
tmp=$(mktemp "$OUT.XXXXXX")
trap 'rm -f "$tmp" "$tmp.next"' EXIT

if [ "${1:-}" = "--rotate" ] || [ ! -f "$OUT" ]; then
  {
    echo "# Generated by scripts/secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Not in git."
    echo "# Rotating these signs everyone out and needs Keycloak re-imported (make clean)."
    for entry in "${SECRETS[@]}"; do
      name=${entry%%=*}
      if [ "$name" = PLATFORM_SECRETS_KEY ] && [ -n "$secrets_key" ]; then
        echo "$name=$secrets_key"
      else
        echo "$name=$(fresh "${entry#*=}")"
      fi
    done
  } > "$tmp"
  made="${#SECRETS[@]} secrets, $( [ "${1:-}" = "--rotate" ] && echo rotated || echo new )"
else
  echo "$OUT exists; keeping its values and adding any that are missing (--rotate to replace)"
  cat "$OUT" > "$tmp"
  # an append must start on a line of its own
  if [ -s "$tmp" ] && [ -n "$(tail -c1 "$tmp")" ]; then echo >> "$tmp"; fi
  for entry in "${SECRETS[@]}"; do
    name=${entry%%=*}
    if ! grep -q "^$name=" "$tmp"; then
      echo "$name=$(fresh "${entry#*=}")" >> "$tmp"
      echo "added $name to $OUT"
    fi
  done
  made="kept, missing ones added"
fi

# An empty value is a missing one (openssl failed now, or an earlier run left NAME=): made again
# in its place, and if it is still empty nothing is written.
for entry in "${SECRETS[@]}"; do
  name=${entry%%=*}
  if [ -z "$(value_in "$name" "$tmp")" ]; then
    value=$(fresh "${entry#*=}")
    if [ -z "$value" ]; then
      echo "$name is empty and could not be generated (does openssl work?); $OUT left as it was" >&2
      exit 1
    fi
    NAME="$name" VALUE="$value" awk 'index($0, ENVIRON["NAME"] "=") == 1 && !done { print ENVIRON["NAME"] "=" ENVIRON["VALUE"]; done = 1; next } { print }' "$tmp" > "$tmp.next"
    mv "$tmp.next" "$tmp"
    echo "generated the empty $name again"
  fi
done
mv "$tmp" "$OUT"
trap - EXIT
echo "wrote $OUT ($made)"

# The one with a shape requirement, checked here rather than discovered by a
# gateway that will not start.
cookie_len=$(awk -F= '/^GATEWAY_COOKIE_SECRET=/{print length($2)}' "$OUT")
if [ "$cookie_len" != "43" ]; then
  echo "GATEWAY_COOKIE_SECRET is $cookie_len characters; oauth2-proxy needs 32 bytes base64url (43)" >&2
  exit 1
fi

# The realm import carries two of them. Rendered, never committed: the template
# holds placeholders so the repo itself has no secret in it.
# shellcheck disable=SC1090
set -a; . "./$OUT"; set +a
python3 - "$TEMPLATE" "$RENDERED" <<'PY'
import os, sys
template, rendered = sys.argv[1], sys.argv[2]
text = open(template, encoding="utf-8").read()
for name in ("GATEWAY_CLIENT_SECRET",):
    value = os.environ.get(name, "")
    if not value:
        raise SystemExit(f"{name} is not set: run scripts/secrets.sh first")
    text = text.replace("__%s__" % name, value)
open(rendered, "w", encoding="utf-8").write(text)
print(f"rendered {rendered} from {template}")
PY
# It holds a client secret, so it stays unreadable to others, except to Keycloak, which runs as
# uid 1000 in its container and reads it at import (without this it fails: Permission denied).
chmod 600 "$RENDERED"
if command -v setfacl >/dev/null 2>&1; then
  setfacl -m u:1000:r "$RENDERED"
else
  echo "setfacl is missing: let uid 1000 (Keycloak) read $RENDERED, or Keycloak will not start" >&2
fi

# compose takes one --env-file, so the settings and the secrets are combined
# into one. Also git-ignored, also regenerated from its two sources.
: > "$COMBINED"
cat env.plugin_downloader "$OUT" >> "$COMBINED"
chmod 600 "$COMBINED"
echo "wrote $COMBINED (env.plugin_downloader + $OUT)"
echo
echo "run the stack with:"
echo "  docker compose -p aisc --env-file $COMBINED -f docker-compose.plugin_downloader.yml \\"
echo "    -f docker-compose-infra.development.yml -f docker-compose.development.yml up -d"
