#!/usr/bin/env bash
# The secrets this install runs on, generated here and never committed.
#
#   ./scripts/secrets.sh            # make them if they are missing
#   ./scripts/secrets.sh --rotate   # make new ones, replacing what is there
#
# A secret committed to the repo is a secret every clone shares. The worst of
# them would be the gateway's cookie secret: whoever holds it can mint a
# session cookie for any user, offline, and that cookie is the session every
# module trusts.
#
# So none of them has a default. The compose files refuse to start without
# these, this writes them once into env.secrets, which is git-ignored, and the
# realm import is rendered from its template with the same values.
#
# PLATFORM_SECRETS_KEY is the exception to --rotate: it encrypts the LLM API keys
# stored in every project's database, so a fresh one would make all of them
# unreadable. --rotate keeps it. To rotate it: prepend a new Fernet key to it
# (comma list, newest first), restart the platform, run
#   python -m platform_service.llm_store rotate
# in the platform container, then drop the old key from the list.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT=env.secrets
COMBINED=env.runtime   # what compose is pointed at: the settings plus the secrets
TEMPLATE=keycloak/aisc-realm.json
RENDERED=keycloak/aisc-realm.local.json

rand()      { openssl rand -hex 32; }
# oauth2-proxy decodes this as base64url and wants exactly 32 bytes out. With
# padding it does not decode, and it then measures the string itself and
# refuses to start: "cookie_secret must be 16, 24, or 32 bytes ... but is 44".
cookie()    { openssl rand -base64 32 | tr '+/' '-_' | tr -d '=\n'; }
# Fernet wants urlsafe base64 of 32 bytes WITH its `=` padding: 44 characters.
fernet()    { openssl rand -base64 32 | tr '+/' '-_' | tr -d '\n'; }

# The LLM keys' encryption key survives --rotate (see the top of this file).
secrets_key=""
if [ -f "$OUT" ]; then
  secrets_key=$(awk -F= '/^PLATFORM_SECRETS_KEY=/{print substr($0, index($0,"=")+1)}' "$OUT")
fi

if [ "${1:-}" = "--rotate" ] || [ ! -f "$OUT" ]; then
  umask 077
  cat > "$OUT" <<EOF
# Generated by scripts/secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Not in git.
# Rotating these signs everyone out and needs Keycloak re-imported (make clean).
GATEWAY_COOKIE_SECRET=$(cookie)
GATEWAY_CLIENT_SECRET=$(rand)
CATALOGUE_INSTALL_TOKEN=$(rand)
DJANGO_SECRET_KEY=$(rand)
INTERNAL_API_KEY=$(rand)
SUPERSET_SECRET_KEY=$(rand)
DASHBOARD_ADMIN_PASSWORD=$(rand)
REPORT_SERVICE_TOKEN=$(rand)
REPORT_RO_PASSWORD=$(rand)
REPORT_COMPOSER_PASSWORD=$(rand)
INSPECTOR_PASSWORD=$(rand)
PLATFORM_CARD_AGENT_TOKEN=$(rand)
PLATFORM_RISK_MAPPER_TOKEN=$(rand)
PLATFORM_SECRETS_KEY=${secrets_key:-$(fernet)}
EOF
  echo "wrote $OUT (14 secrets, $( [ "${1:-}" = "--rotate" ] && echo rotated || echo new ))"

  # The one with a shape requirement, checked here rather than discovered by a
  # gateway that will not start.
  cookie_len=$(awk -F= '/^GATEWAY_COOKIE_SECRET=/{print length($2)}' "$OUT")
  if [ "$cookie_len" != "43" ]; then
    echo "GATEWAY_COOKIE_SECRET is $cookie_len characters; oauth2-proxy needs 32 bytes base64url (43)" >&2
    exit 1
  fi
else
  echo "$OUT exists; leaving it alone (--rotate to replace)"
fi

# Secrets added after this install was made: appended once, never replacing what is there.
for name in REPORT_SERVICE_TOKEN REPORT_RO_PASSWORD REPORT_COMPOSER_PASSWORD INSPECTOR_PASSWORD; do
  if ! grep -q "^$name=" "$OUT"; then
    echo "$name=$(rand)" >> "$OUT"
    echo "added $name to $OUT"
  fi
done
# One token per agentic system, so each agent resolves only its own choice and key.
for name in PLATFORM_CARD_AGENT_TOKEN PLATFORM_RISK_MAPPER_TOKEN; do
  if ! grep -q "^$name=" "$OUT"; then
    echo "$name=$(rand)" >> "$OUT"
    echo "added $name to $OUT"
  fi
done
if ! grep -q "^PLATFORM_SECRETS_KEY=" "$OUT"; then
  echo "PLATFORM_SECRETS_KEY=$(fernet)" >> "$OUT"
  echo "added PLATFORM_SECRETS_KEY to $OUT"
fi

# The realm import carries two of them. Rendered, never committed: the template
# holds placeholders so the repo itself has no secret in it.
# shellcheck disable=SC1090
set -a; . "./$OUT"; set +a
python3 - "$TEMPLATE" "$RENDERED" <<'PY'
import os, sys
template, rendered = sys.argv[1], sys.argv[2]
text = open(template, encoding="utf-8").read()
for name in ("GATEWAY_CLIENT_SECRET",):
    value = os.environ.get(name, "")
    if not value:
        raise SystemExit(f"{name} is not set: run scripts/secrets.sh first")
    text = text.replace("__%s__" % name, value)
open(rendered, "w", encoding="utf-8").write(text)
print(f"rendered {rendered} from {template}")
PY

# compose takes one --env-file, so the settings and the secrets are combined
# into one. Also git-ignored, also regenerated from its two sources.
: > "$COMBINED"
cat env.plugin_downloader "$OUT" >> "$COMBINED"
chmod 600 "$COMBINED"
echo "wrote $COMBINED (env.plugin_downloader + $OUT)"
echo
echo "run the stack with:"
echo "  docker compose -p aisc --env-file $COMBINED \\"
echo "    -f docker-compose-infra.development.yml -f docker-compose.development.yml up -d"
