#!/usr/bin/env bash
# The secrets this install runs on, generated here and never committed.
#
#   ./scripts/secrets.sh            # make them if they are missing
#   ./scripts/secrets.sh --rotate   # make new ones, replacing what is there
#
# Why this exists: the repo used to ship working values for these, so every
# clone of it ran on secrets that anyone could read. The worst of them was the
# gateway's cookie secret: whoever holds it can mint a session cookie for any
# user, offline, and that cookie is now the session every module trusts.
#
# So nothing here has a default any more. The compose files refuse to start
# without these, this writes them once into env.secrets, which is git-ignored,
# and the realm import is rendered from its template with the same values.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT=env.secrets
COMBINED=env.runtime   # what compose is pointed at: the settings plus the secrets
TEMPLATE=keycloak/aisc-realm.json
RENDERED=keycloak/aisc-realm.local.json

rand()      { openssl rand -hex 32; }
# oauth2-proxy decodes this as base64url and wants exactly 32 bytes out. With
# padding it does not decode, and it then measures the string itself and
# refuses to start: "cookie_secret must be 16, 24, or 32 bytes ... but is 44".
cookie()    { openssl rand -base64 32 | tr '+/' '-_' | tr -d '=\n'; }

if [ "${1:-}" = "--rotate" ] || [ ! -f "$OUT" ]; then
  umask 077
  cat > "$OUT" <<EOF
# Generated by scripts/secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Not in git.
# Rotating these signs everyone out and needs Keycloak re-imported (make clean).
GATEWAY_COOKIE_SECRET=$(cookie)
GATEWAY_CLIENT_SECRET=$(rand)
DASHBOARD_OIDC_CLIENT_SECRET=$(rand)
CATALOGUE_INSTALL_TOKEN=$(rand)
DJANGO_SECRET_KEY=$(rand)
INTERNAL_API_KEY=$(rand)
SUPERSET_SECRET_KEY=$(rand)
DASHBOARD_ADMIN_PASSWORD=$(rand)
EOF
  echo "wrote $OUT (8 secrets, $( [ "${1:-}" = "--rotate" ] && echo rotated || echo new ))"

  # The one with a shape requirement, checked here rather than discovered by a
  # gateway that will not start.
  cookie_len=$(awk -F= '/^GATEWAY_COOKIE_SECRET=/{print length($2)}' "$OUT")
  if [ "$cookie_len" != "43" ]; then
    echo "GATEWAY_COOKIE_SECRET is $cookie_len characters; oauth2-proxy needs 32 bytes base64url (43)" >&2
    exit 1
  fi
else
  echo "$OUT exists; leaving it alone (--rotate to replace)"
fi

# The realm import carries two of them. Rendered, never committed: the template
# holds placeholders so the repo itself has no secret in it.
# shellcheck disable=SC1090
set -a; . "./$OUT"; set +a
python3 - "$TEMPLATE" "$RENDERED" <<'PY'
import os, sys
template, rendered = sys.argv[1], sys.argv[2]
text = open(template, encoding="utf-8").read()
for name in ("GATEWAY_CLIENT_SECRET", "DASHBOARD_OIDC_CLIENT_SECRET"):
    value = os.environ.get(name, "")
    if not value:
        raise SystemExit(f"{name} is not set: run scripts/secrets.sh first")
    text = text.replace("__%s__" % name, value)
open(rendered, "w", encoding="utf-8").write(text)
print(f"rendered {rendered} from {template}")
PY

# compose takes one --env-file, so the settings and the secrets are combined
# into one. Also git-ignored, also regenerated from its two sources.
: > "$COMBINED"
cat env.plugin_downloader "$OUT" >> "$COMBINED"
chmod 600 "$COMBINED"
echo "wrote $COMBINED (env.plugin_downloader + $OUT)"
echo
echo "run the stack with:"
echo "  docker compose -p aisc --env-file $COMBINED \\"
echo "    -f docker-compose-infra.development.yml -f docker-compose.development.yml up -d"
